# dvc.yaml
stages:
  process_data:
    cmd: python src/data/make_dataset.py
    deps:
      - src/data/make_dataset.py
      - data/raw/AmesHousing.csv
    outs:
      - data/processed/train.csv
      - data/processed/test.csv
  
  build_features:
    cmd: python src/features/build_features.py
    deps:
      - src/features/build_features.py
      - data/processed/train.csv
      - data/processed/test.csv
    outs:
      - data/processed/X_train_features.csv
      - data/processed/y_train.csv
      - data/processed/X_test_features.csv
      - data/processed/y_test.csv
      - data/processed/preprocessor.pkl
  
  train_model:
    cmd: python src/models/train_model.py
    deps:
      - src/models/train_model.py
      - data/processed/X_train_features.csv
      - data/processed/y_train.csv
    outs:
      - models/best_model.pkl